twig:
    file_name_pattern: '*.twig'
    globals:
        settings: '@App\Service\SiteSettingsService'
        lp: '@App\Service\LandingContentService'

when@test:
    twig:
        strict_variables: true
